# Generated by Django 3.1.2 on 2020-11-04 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_auto_20201104_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='идентификатор пользователя'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 18, 18, 13, 654492, tzinfo=utc)),
        ),
    ]
